### ISSUE TITLE
Implement Replica-Based CanaryUpdate Strategy

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#25]
This strategy will allow users to define a list of steps that they want the controller to run through before promoting a new replica set into the stable replica set. These steps include setting the percentage of traffic between the canary and new replica set, waiting for a user-defined amount of time after the rollout has achieved the desired weights, and pausing the rollout until the user chooses to continue the rollout.

Here is a very high-level overview of the work required:

- [x] Calculate the Replica Counts for the New and Canary (#23)
- [x] Implement the Pause functionality (#28)
- [x] Implement SetWeight functionality (#28)
- [x] Implement the Wait functionality (#28)
- [x] Implement the Scale functionality (#30)
- [ ] Implement the Status functionality including validation of the rollout CRD (#30)
- [x] Add Status changes to Argo CD Lua health script
- [x] Discuss and implement expected behavior of the Argo CD wait command (https://github.com/argoproj/argo-cd/pull/1187)
- [x] Document Canary Strategy (#31)

**Comment by dthomson25** [comment]
Fixed with the PRs listed in the comment above
