### ISSUE TITLE
Change the naming convention for plugins

### ISSUE THREAD

**Issue by meeech** [argoproj/argo-rollouts#2720]
# Summary

The current proposed naming convention is:

`rollouts-my_cool_plugin-<type>-plugin`

This requires using the `_` - motivated by the need to parse out the plugin name from between the 2 dashes. 

Jesse suggested (AR Community meeting: https://youtu.be/wjbGqrVuuDc?t=1299) to use the prefix `rollouts-plugin-<type>` which will then allow any string to come after and simplify any parsing and discoverability.

eg: 
`rollouts-plugin-trafficrouter-foo`
`rollouts-plugin-metric-bar`

Proposal: Update docs and the few plugins already created to use this new naming scheme. 

todo:
- [x] update docs https://argo-rollouts.readthedocs.io/en/latest/plugins/#plugin-repository, https://argo-rollouts.readthedocs.io/en/latest/analysis/plugins/, https://argoproj.github.io/argo-rollouts/features/traffic-management/plugins/
- [x] example  https://github.com/argoproj-labs/rollouts-metric-plugin-sample-prometheus/blob/main/main.go#L4, https://github.com/argoproj-labs/rollouts-metric-plugin-sample-prometheus/blob/main/go.mod#L1 https://github.com/argoproj-labs/rollouts-plugin-metric-sample-prometheus/pull/2

reach out to current plugin repos to let them know

- [x] rollouts-contour-trafficrouter-plugin https://github.com/argoproj-labs/rollouts-contour-trafficrouter-plugin https://github.com/argoproj-labs/rollouts-contour-trafficrouter-plugin/issues/12
- [x] rollouts-opsmx-metric-plugin https://github.com/argoproj-labs/rollouts-opsmx-metric-plugin https://github.com/argoproj-labs/rollouts-opsmx-metric-plugin/issues/3
- [x] rollouts-gatewayapi-trafficrouter-plugin https://github.com/argoproj-labs/rollouts-gatewayapi-trafficrouter-plugin https://github.com/argoproj-labs/rollouts-gatewayapi-trafficrouter-plugin/issues/12
- [x] Reach out to other verticals to put this on their radar. eg: it looks like workflows and cd are starting to introduce plugins https://github.com/argoproj-labs?q=plugin&type=all&language=&sort=
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
